"""Add DailyMemo model for daily memo functionality

Revision ID: 22d22edc25e9
Revises: 8aaa01a42a55
Create Date: 2025-10-11 16:37:35.724984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d22edc25e9'
down_revision: Union[str, Sequence[str], None] = '8aaa01a42a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memo_date', sa.Date(), nullable=False, comment='메모 날짜'),
    sa.Column('content', sa.Text(), nullable=False, comment='메모 내용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_memos_id'), 'daily_memos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_memos_id'), table_name='daily_memos')
    op.drop_table('daily_memos')
    # ### end Alembic commands ###
