"""Update DailyReflection created_at field

Revision ID: 4d731929c2b0
Revises: 1da32c92ae33
Create Date: 2025-10-14 17:54:37.011824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d731929c2b0'
down_revision: Union[str, Sequence[str], None] = '1da32c92ae33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_memos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_reflections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('daily_todos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_todos', 'postpone_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('journeys', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('journeys', 'progress',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('journeys', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journeys', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
    op.alter_column('todos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('journeys', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
    op.alter_column('journeys', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('journeys', 'progress',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('journeys', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('daily_todos', 'postpone_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('daily_todos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('daily_reflections', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('daily_records', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('daily_memos', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    # ### end Alembic commands ###
